name: Sync with Golang Version
on:
  push:
    branches:
      - '*'
    tags:        
      - '*'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:

  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the latest version of Golang
      id: golang_version
      run: |
        echo ::set-output name=GOLANG_VERSION::$(curl -sSL https://golang.org/VERSION?m=text | sed 's/go//g')

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GHUB_TOKEN }}
        custom_tag: ${{ steps.golang_version.outputs.GOLANG_VERSION }}