name: Sync with Golang Version
on:
  push:
    branches:
      - '*'
    tags:        
      - '*'
  schedule:
    - cron: '0 0 1,15 * *'

jobs:

  sync-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get the latest version of Golang
      id: golang_version
      run: |
        VERSION=$(curl https://golang.org/VERSION?m=text)
        echo ::set-output name=GOLANG_VERSION::${VERSION}

    - name: Test output
      id: test_output
      run: |
        echo "${{ steps.git_build_info.outputs.SOURCE_TAG }}"